travel_project/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="home"),
    path("destination/<slug:slug>/", views.destination_detail, name="destination_detail"),
    path('about/', views.about_view, name='about'),
    path('deals/', views.weekly_deals_view, name='deals'),
    path('reservation/', views.reservation_view, name='reservation'),
    path('offers/add/', views.add_weekly_offer, name='add_offer'),
    path('offers/delete/<int:pk>/', views.delete_weekly_offer, name='delete_offer'),
]

travel_project/travel_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('user', include("user.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_project/main/models.py
# main/models.py
from django.db import models
from django.utils.text import slugify


class Destination(models.Model):
    CONTINENT_CHOICES = [
        ("Europe", "Европа"),
        ("Asia", "Азия"),
        ("North America", "Северная Америка"),
        ("South America", "Южная Америка"),
        ("Africa", "Африка"),
        ("Oceania", "Океания"),
    ]

    title = models.CharField(max_length=200, verbose_name="Название")
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name="URL")
    continent = models.CharField(max_length=50, choices=CONTINENT_CHOICES, verbose_name="Континент")
    description = models.TextField(verbose_name="Описание", blank=True)
    population_mil = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Население (млн)", null=True, blank=True)
    area_km2 = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Площадь (км²)", null=True, blank=True)
    gdp_usd = models.DecimalField(max_digits=12, decimal_places=0, verbose_name="ВВП ($)", null=True, blank=True)
    image = models.ImageField(upload_to="destinations/", verbose_name="Изображение", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлено")

    class Meta:
        verbose_name = "Направление"
        verbose_name_plural = "Направления"
        ordering = ["title"]

    def __str__(self):
        return f"{self.title} ({self.continent})"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def formatted_population(self):
        return f"{self.population_mil} млн" if self.population_mil else "—"

    @property
    def formatted_area(self):
        return f"{self.area_km2:,} км²".replace(",", " ") if self.area_km2 else "—"

    @property
    def formatted_gdp(self):
        return f"${self.gdp_usd:,}".replace(",", " ") if self.gdp_usd else "—"


class Place(models.Model):
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE, related_name="places", verbose_name="Страна/направление")
    title = models.CharField(max_length=200, verbose_name="Название места")
    description = models.CharField(max_length=300, blank=True, verbose_name="Описание")
    image = models.ImageField(upload_to="places/", verbose_name="Фото")

    class Meta:
        verbose_name = "Место"
        verbose_name_plural = "Места"

    def __str__(self):
        return f"{self.title} ({self.destination.title})"


from django.db import models

class WeeklyOffer(models.Model):
    title = models.CharField("Название", max_length=200)
    description = models.TextField("Описание", blank=True)
    price = models.DecimalField("Цена (USD)", max_digits=10, decimal_places=2)
    bookings = models.PositiveIntegerField("Количество броней", default=0)
    days = models.PositiveIntegerField("Дней тура", default=1)
    includes_flight = models.BooleanField("Включён перелёт", default=True)
    includes_hotel = models.BooleanField("Включён отель", default=True)
    includes_excursions = models.BooleanField("Включены экскурсии", default=True)
    image = models.ImageField("Изображение", upload_to="offers/", blank=True, null=True)
    destination = models.ForeignKey('Destination', on_delete=models.CASCADE, related_name='weekly_offers')

    def __str__(self):
        return f"{self.title} для {self.destination.title}"

travel_project/main/forms.py
from django import forms
from .models import WeeklyOffer

class WeeklyOfferForm(forms.ModelForm):
    class Meta:
        model = WeeklyOffer
        fields = ['title', 'description', 'price', 'bookings', 'days',
                  'includes_flight', 'includes_hotel', 'includes_excursions', 'image', 'destination']

travel_project/main/views.py
# main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import WeeklyOfferForm



def index(request):
    destinations = Destination.objects.all()
    paginator = Paginator(destinations, 3)  # 3 записи на страницу
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "destinations": destinations[:4],  # первые 4 для баннеров
    }

    return render(request, "main/index.html", context)

def destination_detail(request, slug):
    destination = get_object_or_404(Destination, slug=slug)
    places = destination.places.all()
    weekly_offers = WeeklyOffer.objects.filter(destination=destination).distinct()
    return render(request, "main/destination_detail.html", {
        "destination": destination,
        "weekly_offers": weekly_offers,
        "places": places,
    })


def about_view(request):
    return render(request, 'main/about.html')


from django.shortcuts import render
from .models import WeeklyOffer, Destination

def weekly_deals_view(request):
    offers = WeeklyOffer.objects.select_related('destination').all()

    # Получаем уникальные направления из всех офферов
    destinations = Destination.objects.filter(weekly_offers__in=offers).distinct()

    destination_slug = request.GET.get('destination')
    price_range = request.GET.get('price_range')

    if destination_slug:
        offers = offers.filter(destination__slug=destination_slug)

    if price_range:
        try:
            if price_range == "2500+":
                offers = offers.filter(price__gte=2500)
            else:
                min_price, max_price = map(int, price_range.split('-'))
                offers = offers.filter(price__gte=min_price, price__lte=max_price)
        except ValueError:
            pass

    return render(request, 'main/deals.html', {
        'offers': offers,
        'destinations': destinations,
    })


def reservation_view(request):
    return render(request, 'main/reservation.html')




def is_manager(user):
    # приводим роль к нижнему регистру для надёжности
    return user.role.lower() == 'manager' or user.is_superuser


from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

@login_required
@user_passes_test(is_manager)
def add_weekly_offer(request):
    if request.method == 'POST':
        form = WeeklyOfferForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "✅ Предложение добавлено")
            return redirect('home')  # или куда хочешь
    else:
        form = WeeklyOfferForm()
    return render(request, 'main/add_offer.html', {'form': form})


@login_required
@user_passes_test(is_manager)
def delete_weekly_offer(request, pk):
    offer = get_object_or_404(WeeklyOffer, pk=pk)

    if request.method == 'POST':
        offer.delete()
        messages.success(request, "🗑️ Предложение удалено")
        return redirect('home')

    # Можно сделать страницу подтверждения удаления, но если не нужна, редирект
    return redirect('home')

travel_project/main/templates/main/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}О нас | Arlen and Ilimbek{% endblock %}
{% block nav_about %}active{% endblock %}

{% block content %}
<section class="about-section" style="padding: 60px 0; background: #f9f9f9;">
  <div class="container">
    <div class="section-heading text-center">
      <h2>О проекте WoOx Travel</h2>
      <p>Сайт для бронирования путешествий и отпусков — быстро, удобно и надёжно.</p>
    </div>
    <div class="row" style="margin-top: 40px;">
      <div class="col-lg-6">
        <img src="{% static 'assets/images/about-photo.jpg' %}" alt="Создатель сайта" style="width: 100%; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
      </div>
      <div class="col-lg-6">
        <h3>Привет!</h3>
        <p><p>Мы — создатели этого проекта: Арлен и Илимбек. Нам нравится помогать людям открывать новые страны и планировать незабываемые отпуска. Этот сайт — наш способ сделать бронирование путешествий максимально простым и приятным.</p>

<p>WoOx Travel предлагает удобный интерфейс для выбора направлений, просмотра эксклюзивных предложений, а также лёгкое бронирование туров и отелей. На сайте собраны лучшие места для отдыха, а также еженедельные акции и специальные предложения, которые помогут сделать ваш отдых ещё выгоднее и интереснее.</p>

<p>Спасибо, что посетили наш сайт! Если у вас есть вопросы или предложения, не стесняйтесь связаться с нами — мы всегда рады помочь!</p>
</p>
        <div class="main-button" style="margin-top: 30px;">
          <a href="{% url 'home' %}">Вернуться на главную</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

travel_project/main/templates/main/add_offer.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Добавить предложение недели</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Добавить</button>
    </form>
</div>
{% endblock %}

travel_project/main/templates/main/deals.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-heading">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4>Откройте для себя наши еженедельные предложения</h4>
        <h2>Удивительные цены и многое другое</h2>
        <div class="border-button"><a href="{% url 'about' %}">Узнать больше</a></div>
      </div>
    </div>
  </div>
</div>

{% if request.user.is_authenticated and request.user.role|lower == 'manager' %}
<div class="container text-end my-4">
  <a href="{% url 'add_offer' %}" class="btn btn-success">Добавить предложение</a>
</div>
{% endif %}

<div class="search-form">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <form id="search-form" name="gs" method="get" role="search" action=".">
          <div class="row">
            <div class="col-lg-2">
              <h4>Сортировать предложения по:</h4>
            </div>
            <div class="col-lg-4">
              <fieldset>
                <select class="form-select" name="destination">
                  <option selected disabled>Направления</option>
                  {% for dest in destinations %}
                    <option value="{{ dest.slug }}" {% if request.GET.destination == dest.slug %}selected{% endif %}>{{ dest.title }}</option>
                  {% endfor %}
                </select>
              </fieldset>
            </div>
            <div class="col-lg-4">
              <fieldset>
                <select class="form-select" name="price_range">
                  <option selected disabled>Диапазон цен</option>
                  <option value="100-250" {% if request.GET.price_range == "100-250" %}selected{% endif %}>$100 - $250</option>
                  <option value="250-500" {% if request.GET.price_range == "250-500" %}selected{% endif %}>$250 - $500</option>
                  <option value="500-1000" {% if request.GET.price_range == "500-1000" %}selected{% endif %}>$500 - $1,000</option>
                  <option value="1000-2500" {% if request.GET.price_range == "1000-2500" %}selected{% endif %}>$1,000 - $2,500</option>
                  <option value="2500+" {% if request.GET.price_range == "2500+" %}selected{% endif %}>$2,500 и выше</option>
                </select>
              </fieldset>
            </div>
            <div class="col-lg-2">
              <fieldset>
                <button type="submit" class="border-button">Показать результаты</button>
              </fieldset>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="amazing-deals">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3">
        <div class="section-heading text-center">
          <h2>Лучшие еженедельные предложения в каждом городе</h2>
          <p>Откройте для себя лучшие туристические предложения, подобранные специально для вас.</p>
        </div>
      </div>

      {% for offer in offers %}
      <div class="col-lg-6 col-sm-6">
        <div class="item">
          <div class="row">
            <div class="col-lg-6">
              <div class="image">
                {% if offer.image %}
                  <img src="{{ offer.image.url }}" alt="{{ offer.title }}">
                {% else %}
                  <img src="{% static 'images/default-offer.jpg' %}" alt="Стандартное предложение">
                {% endif %}
              </div>
            </div>
            <div class="col-lg-6 align-self-center">
              <div class="content">
                <span class="info">*Специальное еженедельное предложение</span>
                <h4>{{ offer.title }}</h4>
                <div class="row">
                  <div class="col-6">
                    <i class="fa fa-clock"></i>
                    <span class="list">{{ offer.days }} дней</span>
                  </div>
                  <div class="col-6">
                    <i class="fa fa-map"></i>
                    <span class="list">{{ offer.destination.title }}</span>
                  </div>
                </div>
                <p>{{ offer.description|truncatewords:20 }}</p>
                <p><strong>${{ offer.price }}</strong></p>
                <div class="main-button mb-2">
                  <a href="{% url 'reservation' %}">Подробнее о направлении</a>
                </div>

{% if request.user.is_authenticated and request.user.role|lower == 'manager' %}


{% endif %}



{% if request.user.is_authenticated and request.user.role|lower == 'manager' %}
<form action="{% url 'delete_offer' offer.id %}" method="post" onsubmit="return confirm('Удалить это предложение?');">
  {% csrf_token %}
  <button type="submit" class="btn btn-sm btn-outline-danger">Удалить</button>
</form>
{% endif %}

              </div>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <p>По вашему запросу не найдено предложений.</p>
      {% endfor %}
    </div>
  </div>
</div>

<div class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2>Хотите отправиться в путешествие?</h2>
        <h4>Забронируйте тур, нажав на кнопку</h4>
      </div>
      <div class="col-lg-4">
        <div class="border-button">
          <a href="#">Забронировать сейчас</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

travel_project/main/templates/main/index.html
{% extends "base.html" %}

{% load static %}  {# load static должен быть в начале шаблона, сразу после extends #}

{% block title %}Главная | WoOx Travel{% endblock %}
{% block nav_home %}active{% endblock %}

{% block content %}

<!-- ***** Главный баннер (Начало) ***** -->
<section id="section-1">
  <div class="content-slider">
    <input type="radio" id="banner1" class="sec-1-input" name="banner" checked>
    <input type="radio" id="banner2" class="sec-1-input" name="banner">
    <input type="radio" id="banner3" class="sec-1-input" name="banner">
    <input type="radio" id="banner4" class="sec-1-input" name="banner">

    <!-- Баннеры с проверками наличия объекта и slug -->
    <div class="slider">

      {% if destinations|length > 0 and destinations.0.slug %}
      <!-- Баннер 1 -->
      <div id="top-banner-1" class="banner" style="background-image: url('{{ destinations.0.image.url }}');">
        <div class="banner-inner-wrapper header-text">
          <div class="main-caption">
            <h2>Откройте для себя прекрасную страну:</h2>
            <h1>{{ destinations.0.title }}</h1>
            <div class="border-button"><a href="{% url 'destination_detail' destinations.0.slug %}">Подробнее</a></div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="more-info">
                  <div class="row">
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-user"></i>
                      <h4><span>Население:</span><br>{{ destinations.0.formatted_population }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-globe"></i>
                      <h4><span>Территория:</span><br>{{ destinations.0.formatted_area }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-home"></i>
                      <h4><span>ВВП:</span><br>{{ destinations.0.formatted_gdp }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <div class="main-button">
                        <a href="{% url 'destination_detail' destinations.0.slug %}">Узнать больше</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      {% if destinations|length > 1 and destinations.1.slug %}
      <!-- Баннер 2 -->
      <div id="top-banner-2" class="banner" style="background-image: url('{{ destinations.1.image.url }}');">
        <div class="banner-inner-wrapper header-text">
          <div class="main-caption">
            <h2>Откройте для себя прекрасную страну:</h2>
            <h1>{{ destinations.1.title }}</h1>
            <div class="border-button"><a href="{% url 'destination_detail' destinations.1.slug %}">Подробнее</a></div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="more-info">
                  <div class="row">
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-user"></i>
                      <h4><span>Население:</span><br>{{ destinations.1.formatted_population }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-globe"></i>
                      <h4><span>Территория:</span><br>{{ destinations.1.formatted_area }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-home"></i>
                      <h4><span>ВВП:</span><br>{{ destinations.1.formatted_gdp }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <div class="main-button">
                        <a href="{% url 'destination_detail' destinations.1.slug %}">Узнать больше</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      {% if destinations|length > 2 and destinations.2.slug %}
      <!-- Баннер 3 -->
      <div id="top-banner-3" class="banner" style="background-image: url('{{ destinations.2.image.url }}');">
        <div class="banner-inner-wrapper header-text">
          <div class="main-caption">
            <h2>Откройте для себя прекрасную страну:</h2>
            <h1>{{ destinations.2.title }}</h1>
            <div class="border-button"><a href="{% url 'destination_detail' destinations.2.slug %}">Подробнее</a></div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="more-info">
                  <div class="row">
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-user"></i>
                      <h4><span>Население:</span><br>{{ destinations.2.formatted_population }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-globe"></i>
                      <h4><span>Территория:</span><br>{{ destinations.2.formatted_area }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-home"></i>
                      <h4><span>ВВП:</span><br>{{ destinations.2.formatted_gdp }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <div class="main-button">
                        <a href="{% url 'destination_detail' destinations.2.slug %}">Узнать больше</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      {% if destinations|length > 3 and destinations.3.slug %}
      <!-- Баннер 4 -->
      <div id="top-banner-4" class="banner" style="background-image: url('{{ destinations.3.image.url }}');">
        <div class="banner-inner-wrapper header-text">
          <div class="main-caption">
            <h2>Откройте для себя прекрасную страну:</h2>
            <h1>{{ destinations.3.title }}</h1>
            <div class="border-button"><a href="{% url 'destination_detail' destinations.3.slug %}">Подробнее</a></div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="more-info">
                  <div class="row">
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-user"></i>
                      <h4><span>Население:</span><br>{{ destinations.3.formatted_population }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-globe"></i>
                      <h4><span>Территория:</span><br>{{ destinations.3.formatted_area }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <i class="fa fa-home"></i>
                      <h4><span>ВВП:</span><br>{{ destinations.3.formatted_gdp }}</h4>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-6">
                      <div class="main-button">
                        <a href="{% url 'destination_detail' destinations.3.slug %}">Узнать больше</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

    </div>

    <!-- Переключатели -->
    <nav>
      <div class="controls">
        <label for="banner1"><span class="progressbar"><span class="progressbar-fill"></span></span><span class="text">1</span></label>
        <label for="banner2"><span class="progressbar"><span class="progressbar-fill"></span></span><span class="text">2</span></label>
        <label for="banner3"><span class="progressbar"><span class="progressbar-fill"></span></span><span class="text">3</span></label>
        <label for="banner4"><span class="progressbar"><span class="progressbar-fill"></span></span><span class="text">4</span></label>
      </div>
    </nav>
  </div>
</section>
<!-- ***** Главный баннер (Конец) ***** -->



<!-- ***** Страны ***** -->
<div class="visit-country">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <div class="section-heading">
          <h2>Посетите одну из наших стран</h2>
          <p>Лучшие направления для путешествий и незабываемых впечатлений.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <!-- Список направлений -->
      <div class="col-lg-8">
        <div class="items">
          {% for dest in page_obj %}
            <div class="item {% if forloop.last %}last-item{% endif %}">
              <div class="row">
                <div class="col-lg-4 col-sm-5">
                  <div class="image">
                    {% if dest.image %}
                      <img src="{{ dest.image.url }}" alt="{{ dest.title }}">
                    {% else %}
                      <img src="{% static 'assets/images/default-country.jpg' %}" alt="{{ dest.title }}">
                    {% endif %}
                  </div>
                </div>
                <div class="col-lg-8 col-sm-7">
                  <div class="right-content">
                    <h4>{{ dest.title }}</h4>
                    <span>{{ dest.get_continent_display }}</span>
                    <div class="main-button">
                      <a href="{% url 'destination_detail' dest.slug %}">Подробнее</a>
                    </div>
                    <p>{{ dest.description|truncatewords:20 }}</p>
                    <ul class="info">
                      <li><i class="fa fa-user"></i> {{ dest.formatted_population }}</li>
                      <li><i class="fa fa-globe"></i> {{ dest.formatted_area }}</li>
                      <li><i class="fa fa-home"></i> {{ dest.formatted_gdp }}</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          {% empty %}
            <p>Направления не найдены.</p>
          {% endfor %}
        </div>

        <!-- Пагинация -->
        <ul class="page-numbers">
          {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-left"></i></a></li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="active"><a href="?page={{ num }}">{{ num }}</a></li>
            {% else %}
              <li><a href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-arrow-right"></i></a></li>
          {% endif %}
        </ul>
      </div>

      <!-- Карта -->
      <div class="col-lg-4">
        <div class="side-bar-map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18..."
            width="100%" height="550px" style="border:0; border-radius:23px;" allowfullscreen=""
            loading="lazy" referrerpolicy="no-referrer-when-downgrade">
          </iframe>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- ***** Призыв к действию ***** -->
<div class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2>Хотите отправиться в путешествие?</h2>
        <h4>Забронируйте поездку прямо сейчас!</h4>
      </div>
      <div class="col-lg-4">
        <div class="border-button">
          <a href="/reservation/">Забронировать</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Скрипты для работы сайта -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/isotope.min.js' %}"></script>
<script src="{% static 'assets/js/owl-carousel.js' %}"></script>
<script src="{% static 'assets/js/wow.js' %}"></script>
<script src="{% static 'assets/js/tabs.js' %}"></script>
<script src="{% static 'assets/js/popup.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>

<script>
  function bannerSwitcher() {
    let next = document.querySelector('.sec-1-input:checked').nextElementSibling;
    if (next && next.classList.contains('sec-1-input')) {
      next.checked = true;
    } else {
      document.querySelectorAll('.sec-1-input')[0].checked = true;
    }
  }
  setInterval(bannerSwitcher, 5000);
</script>

{% endblock %}